title = 'Jeremy Crosbie'
baseURL = "https://jeremycrosbie.com"
theme = 'ananke'
enableRobotsTXT = true

[params]
featured_image_class = "jc-site-image"
cover_dimming_class = "jc-site-image-dimming"
custom_css = ["custom.scss"]
recent_posts_number = 3
favicon = '/favicon.ico'
